### ISSUE TITLE
Expected end of line but found identifier.

### ISSUE THREAD

**Issue by lamw** [msabramo/skype-applescripts#1]
I tried to compile the script on macOS 10.12 system, but it keeps throwing following:

`Expected end of line but found identifier.`  and highlighting following line:

`set status to send command "GET USERSTATUS" script name script_name`

Any thoughts?

**Comment by msabramo** [comment]
Hmmm, I'm getting the same error on OS 10.14.6...

**Comment by msabramo** [comment]
I got past that error by downgrading from Skype 8 to Skype 7.

```
brew cask uninstall skype
brew cask install skype7
```

It seems that Skype 8 removed AppleScript support.

See: https://answers.microsoft.com/en-us/skype/forum/all/skype-8-not-scriptable/0a5e4fe4-87d9-4e45-86c0-ce00d224087f
